BEGIN

    SET @DESPESA_TOTAL = (
            IFNULL(NEW.DESPESA_LUZ_MEDIA_MENSAL, 0)
                +
            IFNULL(NEW.DESPESA_AGUA_MEDIA_MENSAL, 0)
                +
            IFNULL(NEW.DESPESA_GAS_MEDIA_MENSAL, 0)
                +
            IFNULL(NEW.DESPESA_ALUGUEL, 0)
                +
            IFNULL(NEW.DESPESA_FINANCIAMENTO_TIPO, 0)              
              	+
            IFNULL(NEW.DESPESA_FINANCIAMENTO_RESIDENCIAL_PARCELA, 0)
                +
            IFNULL(NEW.DESPESA_FINANCIAMENTO_VEICULO_PARCELA, 0)
                +
            IFNULL(NEW.DESPESA_IPTU, 0)
                +
            IFNULL(NEW.DESPESA_IPVA, 0)
                +
            IFNULL(NEW.DESPESA_EMPRESTIMO_PARCELA, 0)
                +
            IFNULL(NEW.DESPESA_INTERNET_TELEVISAO, 0)
                +
            IFNULL(NEW.DESPESA_CELULAR, 0)
                +
            IFNULL(NEW.DESPESA_MEDIA_MERCADO, 0)
                +
            IFNULL(NEW.DESPESA_MEDICAMENTOS, 0)
                +
            IFNULL(NEW.DESPESA_PLANO_SAUDE_MENSAL, 0)
                +
            IFNULL(NEW.DESPESA_INSS, 0)
                +
            IFNULL(NEW.DESPESA_LAZER, 0)
                +
            IFNULL(NEW.DESPESA_COMBUSTIVEL, 0)
                +
            IFNULL(NEW.DESPESA_CARTAO_FATURA, 0)
                +
            IFNULL(NEW.DESPESA_VEICULO_ALUGADO_MENSALIDADE, 0)
                +
            IFNULL(NEW.DESPESA_VEICULO_ALUGADO_MENSALIDADE, 0)
                +
            IFNULL(NEW.DESPESA_SEGURO_VIDA_MENSAL, 0)
                +
            IFNULL(NEW.DESPESA_CONDOMINIO_MENSAL, 0)
                +
            IFNULL(NEW.DESPESA_CONTRIBUICAO_SINDICAL, 0)
                +
            IFNULL(NEW.DESPESA_ESCOLA_MENSAL, 0)
                +
            IFNULL(NEW.DESPESA_UNIVERSIDADE_MENSAL, 0)
                +
            IFNULL(NEW.DESPESA_CLUBE_MENSALIDADE, 0)
        		+
        	IFNULL(NEW.DESPESA_PERSONALIZADA, 0)
        );

    SET @DIVIDAS_TOTAIS = (
            IFNULL(NEW.DIVIDA_FINANCIAMENTO_RESIDENCIAL_SALDO_DEVEDOR, 0)
                +
            IFNULL(NEW.DIVIDA_FINANCIAMENTO_VEICULO_SALDO_DEVEDOR, 0)
                +
            IFNULL(NEW.DIVIDA_EMPRESTIMO_SALDO_DEVEDOR, 0)
                +
            IFNULL(NEW.DIVIDA_CARTAO_FATURA_SALDO_DEVEDOR, 0)
       			+
        	IFNULL(NEW.DIVIDA_PERSONALIZADA, 0)
    		
    );


	SET @INDICE_POUPANCA           = (IFNULL(NEW.RECEITA_RENDA_MENSAL_LIQUIDA, 0) - @DESPESA_TOTAL) / NEW.RECEITA_RENDA_MENSAL_LIQUIDA;
    SET @INDICE_LIQUIDEZ_CORRENTE  = NEW.RECEITA_RENDA_MENSAL_LIQUIDA/IFNULL(@DIVIDAS_TOTAIS, 1);
    SET @INDICE_ENDIVIDAMENTO      = @DESPESA_TOTAL / NEW.RECEITA_APLICACOES_VALOR_TOTAL;
    SET @INDICE_COBERTURA          = ROUND(NEW.RECEITA_RENDA_MENSAL_LIQUIDA /(@DESPESA_TOTAL + @DIVIDAS_TOTAIS), 0);
    SET @PATRIMONIO_LIQUIDO        = IFNULL(NEW.RECEITA_APLICACOES_VALOR_TOTAL, 0) - @DESPESA_TOTAL;


    INSERT INTO
    	CLIENTES_RESULTADOS
        	(
                CLIENTE_FORMULARIO_FK,
                DATA,
                INDICE_POUPANCA,
                INDICE_LIQUIDEZ_CORRENTE,
                INDICE_ENDIVIDAMENTO,
                INDICE_COBERTURA,
                PATRIMONIO_LIQUIDO
            )
    VALUES
    	(
        	NEW.PK,
            NOW(),
            @INDICE_POUPANCA,
            @INDICE_LIQUIDEZ_CORRENTE,
            @INDICE_ENDIVIDAMENTO,
            @INDICE_COBERTURA,
            @PATRIMONIO_LIQUIDO
        );
    
END

BEGIN
    UPDATE CLIENTES_RESULTADOS

    SET DESPESA_TOTAL = (
            IFNULL(NEW.DESPESA_LUZ_MEDIA_MENSAL, 0)
                +
            IFNULL(NEW.DESPESA_AGUA_MEDIA_MENSAL, 0)
                +
            IFNULL(NEW.DESPESA_GAS_MEDIA_MENSAL, 0)
                +
            IFNULL(NEW.DESPESA_ALUGUEL, 0)
                +
            IFNULL(NEW.DESPESA_FINANCIAMENTO_TIPO, 0)
                +
            IFNULL(NEW.DESPESA_FINANCIAMENTO_RESIDENCIAL_PARCELA, 0)
                +
            IFNULL(NEW.DESPESA_FINANCIAMENTO_VEICULO_PARCELA, 0)
                +
            IFNULL(NEW.DESPESA_IPTU, 0)
                +
            IFNULL(NEW.DESPESA_IPVA, 0)
                +
            IFNULL(NEW.DESPESA_EMPRESTIMO_PARCELA, 0)
                +
            IFNULL(NEW.DESPESA_INTERNET_TELEVISAO, 0)
                +
            IFNULL(NEW.DESPESA_CELULAR, 0)
                +
            IFNULL(NEW.DESPESA_MEDIA_MERCADO, 0)
                +
            IFNULL(NEW.DESPESA_MEDICAMENTOS, 0)
                +
            IFNULL(NEW.DESPESA_PLANO_SAUDE_MENSAL, 0)
                +
            IFNULL(NEW.DESPESA_INSS, 0)
                +
            IFNULL(NEW.DESPESA_LAZER, 0)
                +
            IFNULL(NEW.DESPESA_COMBUSTIVEL, 0)
                +
            IFNULL(NEW.DESPESA_CARTAO_FATURA, 0)
                +
            IFNULL(NEW.DESPESA_VEICULO_ALUGADO_MENSALIDADE, 0)
                +
            IFNULL(NEW.DESPESA_VEICULO_ALUGADO_MENSALIDADE, 0)
                +
            IFNULL(NEW.DESPESA_SEGURO_VIDA_MENSAL, 0)
                +
            IFNULL(NEW.DESPESA_CONDOMINIO_MENSAL, 0)
                +
            IFNULL(NEW.DESPESA_CONTRIBUICAO_SINDICAL, 0)
                +
            IFNULL(NEW.DESPESA_ESCOLA_MENSAL, 0)
                +
            IFNULL(NEW.DESPESA_UNIVERSIDADE_MENSAL, 0)
                +
            IFNULL(NEW.DESPESA_CLUBE_MENSALIDADE, 0)
                +
            IFNULL(NEW.DESPESA_PERSONALIZADA_FK, 0)
        		+
        	IFNULL(NEW.DESPESA_PERSONALIZADA, 0)
        );

    SET DIVIDAS_TOTAIS = (
            IFNULL(NEW.DIVIDA_FINANCIAMENTO_RESIDENCIAL_SALDO_DEVEDOR, 0)
                +
            IFNULL(NEW.DIVIDA_FINANCIAMENTO_VEICULO_SALDO_DEVEDOR, 0)
                +
            IFNULL(NEW.DIVIDA_EMPRESTIMO_SALDO_DEVEDOR, 0)
                +
            IFNULL(NEW.DIVIDA_CARTAO_FATURA_SALDO_DEVEDOR, 0)
       			+
        	IFNULL(NEW.DIVIDA_PERSONALIZADA, 0)
    		
    );



    SET
        INDICE_POUPANCA = (IFNULL(NEW.RECEITA_RENDA_MENSAL_LIQUIDA, 0) - DESPESA_TOTAL) / NEW.RECEITA_RENDA_MENSAL_LIQUIDA,
        INDICE_LIQUIDEZ_CORRENTE = NEW.RECEITA_RENDA_MENSAL_LIQUIDA / IFNULL(DIVIDAS_TOTAIS, 1),
        INDICE_ENDIVIDAMENTO = DESPESA_TOTAL / NEW.RECEITA_APLICACOES_VALOR_TOTAL,
        INDICE_COBERTURA = ROUND(NEW.RECEITA_RENDA_MENSAL_LIQUIDA / (DESPESA_TOTAL + DIVIDAS_TOTAIS), 0),
        PATRIMONIO_LIQUIDO = IFNULL(NEW.RECEITA_APLICACOES_VALOR_TOTAL, 0) - DESPESA_TOTAL
    WHERE CLIENTE_FORMULARIO_FK = NEW.PK;
END



 IFNULL(NEW.DIVIDA_CARTAO_FATURA_SALDO_DEVEDOR, 0) + IFNULL(NEW.DIVIDA_PERSONALIZADA, 0) ); UPDATE CLIENTES_RESULTADOS SET SET @INDICE_POUPANCA = (IFNULL(NEW.RECEITA_RENDA_MENSAL_LIQUIDA, 0) - DESPESA_TOTAL) / NEW.RECEITA_RENDA_MENSAL_LIQUIDA, SET @INDICE_LIQUIDEZ_CORRENTE = NEW.RECEITA_RENDA_MENSAL_LIQUIDA / IFNULL(DIVIDAS_TOTAIS, 1), SET @INDICE_ENDIVIDAMENTO = DESPESA_TOTAL / NEW.RECEITA_APLICACOES_VALOR_TOTAL, SET @INDICE_COBERTURA = ROUND(NEW.RECEITA_RENDA_MENSAL_LIQUIDA / (DESPESA_TOTAL + DIVIDAS_TOTAIS), 0), SET @PATRIMONIO_LIQUIDO = IFNULL(NEW.RECEITA_APLICACOES_VALOR_TOTAL, 0) - DESPESA_TOTAL WHERE CLIENTE_FORMULARIO_FK = NEW.PK; END"
Mensagem do MySQL: #1064 - Você tem um erro de sintaxe no seu SQL próximo a 'SET @INDICE_POUPANCA = (IFNULL(NEW.RECEITA_RENDA_MENSAL_LIQUIDA, 0) - DESPESA_TO' na linha 79